# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: secrets-cli
    id: linux
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/madwire-media/secrets-cli/vars.BuildVersion={{ .Version }}
      - -X github.com/madwire-media/secrets-cli/vars.BuildCommit={{ .Commit }}
  - binary: secrets-cli
    id: windows
    goos:
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/madwire-media/secrets-cli/vars.BuildVersion={{ .Version }}
      - -X github.com/madwire-media/secrets-cli/vars.BuildCommit={{ .Commit }}
  - binary: secrets-cli
    id: macos-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/madwire-media/secrets-cli/vars.BuildVersion={{ .Version }}
      - -X github.com/madwire-media/secrets-cli/vars.BuildCommit={{ .Commit }}
    hooks:
      post:
        - gon .gon-amd64.json
        - mv dist/secrets-cli-macos-amd64.dmg dist/secrets-cli_{{ .Version }}_darwin_amd64.dmg
  - binary: secrets-cli
    id: macos-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/madwire-media/secrets-cli/vars.BuildVersion={{ .Version }}
      - -X github.com/madwire-media/secrets-cli/vars.BuildCommit={{ .Commit }}
    hooks:
      post:
        - gon .gon-arm64.json
        - mv dist/secrets-cli-macos-arm64.dmg dist/secrets-cli_{{ .Version }}_darwin_arm64.dmg
archives:
  - id: linux-archive
    builds:
      - linux
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
  - id: windows-archive
    builds:
      - windows
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
  - id: darwin-archive
    builds:
      - macos-amd64
      - macos-arm64
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
release:
  ids:
    - linux-archive
    - windows-archive
  extra_files:
    - glob: ./dist/*.dmg
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
